# Generated by Django 2.1.2 on 2019-01-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='profile_pix'),
        ),
    ]
