# Generated by Django 2.1.2 on 2019-03-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_friends_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='current_user',
        ),
    ]
