# Generated by Django 2.1.2 on 2019-03-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_message_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='User1',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='User2',
            new_name='sender',
        ),
    ]
