# Generated by Django 2.1.2 on 2019-03-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_tweet_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='friend',
        ),
    ]
