# Generated by Django 2.1.2 on 2019-03-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_tweet_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Friends'),
        ),
    ]
