# Generated by Django 2.1.2 on 2019-03-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_tweet_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='friend',
        ),
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
