# Generated by Django 2.1.2 on 2019-02-04 18:13

import dara.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=models.SET(dara.models.set_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
